name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          ~/satysfi
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v4
    - name: clone satysfi-package
      run: |
        if [ ! -d ~/satysfi ]; then
          git clone https://github.com/gfngfn/SATySFi.git ~/satysfi
        fi
    - name: copy satysfi-package
      run: mkdir -p ~/.satysfi/dist/packages/ && cp ~/satysfi/lib-satysfi/dist/packages/* ~/.satysfi/dist/packages/
    - name: Run tests
      run: cargo test --verbose

